const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const path=require('path');const {JSDOM}=require('jsdom');
const {promptFor,chatLink}=require('../docs/watch-research.js');
function boot(){const dom=new JSDOM(fs.readFileSync(path.join(__dirname,'../docs/index.html'),'utf8'),{url:'https://local.test/#opportunity',runScripts:'outside-only'});const w=dom.window,d=w.document;w.fetch=()=>{throw Error('No API call allowed');};w.localStorage.setItem('private-memo','SECRET_NOTE');for(const f of ['opportunity-rules.js','opportunity-stories-data.js','opportunity-stories.js','opportunity.js','watch-research.js'])w.eval(fs.readFileSync(path.join(__dirname,'../docs',f),'utf8'));return {w,d,close:()=>w.close()};}
test('market and company buttons generate distinct questions without personal storage',()=>{const c=boot();try{c.d.querySelector('[data-chat-context=market]').click();assert.match(c.d.querySelector('.research-editor').value,/米国株/);c.d.querySelector('[data-chat-context=SBUX]').click();const p=c.d.querySelector('.research-editor').value;assert.match(p,/Starbucks/);assert.match(p,/ファンダメンタル/);assert.match(p,/テクニカル/);assert.doesNotMatch(p,/SECRET_NOTE/);assert.match(p,/最新とは限りません/);assert.equal(new URL(c.d.querySelector('[data-chat-open]').href).searchParams.get('q'),p);}finally{c.close();}});
test('SBUX questions distinguish CEO changes, revenue causes, and conditional divestiture accounting',()=>{const c=boot();try{for(const [topic,expected] of [['ceo',/前任のCEO/],['revenue',/連結範囲/],['japan',/未確定なら仮定/]]){c.d.querySelector(`[data-chat-topic=${topic}]`).click();assert.match(c.d.querySelector('.research-editor').value,expected);}const p=c.d.querySelector('.research-editor').value;for(const word of ['売却代金','売却益','連結売上','ロイヤルティ'])assert(p.includes(word));}finally{c.close();}});
test('edited questions survive topic switch, closing, and background market renders',()=>{const c=boot();try{c.d.querySelector('[data-chat-topic=ceo]').click();const editor=c.d.querySelector('.research-editor');editor.value='自分で追加した質問';editor.dispatchEvent(new c.w.Event('input'));c.w.dispatchEvent(new c.w.Event('watch-data'));assert.equal(editor.value,'自分で追加した質問');c.d.querySelector('[data-chat-topic=japan]').click();c.d.querySelector('[data-chat-topic=ceo]').click();assert.equal(editor.value,'自分で追加した質問');c.d.querySelector('[data-chat-close]').click();c.d.querySelector('[data-chat-topic=ceo]').click();assert.equal(editor.value,'自分で追加した質問');}finally{c.close();}});
test('clipboard success and denial both allow transferring the full question',async()=>{const c=boot();try{c.d.querySelector('[data-chat-topic=japan]').click();const e=c.d.querySelector('.research-editor');let copied;Object.defineProperty(c.w.navigator,'clipboard',{value:{writeText:async t=>{copied=t;}},configurable:true});await c.d.querySelector('[data-chat-copy]').onclick();assert.equal(copied,e.value);Object.defineProperty(c.w.navigator,'clipboard',{value:undefined});await c.d.querySelector('[data-chat-copy]').onclick();assert.equal(e.selectionEnd,e.value.length);assert.match(c.d.querySelector('#research-panel [role=status]').textContent,/自動コピーできません/);}finally{c.close();}});
test('long/empty/unusual questions are not truncated or turned into unsafe URLs',()=>{const c=boot();try{c.d.querySelector('[data-chat-context=market]').click();const e=c.d.querySelector('.research-editor'),a=c.d.querySelector('[data-chat-open]');e.value='長'.repeat(5000);e.dispatchEvent(new c.w.Event('input'));assert.equal(a.href,'https://chatgpt.com/');assert.equal(e.value.length,5000);e.value=' ';e.dispatchEvent(new c.w.Event('input'));assert.equal(a.hasAttribute('href'),false);assert(a.rel.includes('noreferrer'));assert.equal(new URL(chatLink('a & q=evil # <script>')).searchParams.get('q'),'a & q=evil # <script>');assert.doesNotThrow(()=>chatLink('\ud800'));}finally{c.close();}});
test('switching companies replaces subject and hides SBUX-only topic',()=>{const c=boot();try{c.d.querySelector('.story-choice[data-story=GOOGL]').click();c.d.querySelector('[data-chat-context=GOOGL]').click();assert.match(c.d.querySelector('.research-editor').value,/Alphabet/);assert.doesNotMatch(c.d.querySelector('[data-chat-topics]').textContent,/日本事業/);assert.match(promptFor('market','overview',null,{date:'2026-09-17',overall_trend_state:'correction'},'2026-09-18'),/2026-09-17/);}finally{c.close();}});
